version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: ChartGenerator-Chart.js
    versions:
    - 0.0.69
